### ISSUE TITLE
Write a short sentence for every plugin

### ISSUE THREAD

**Issue by digitarald** [mozilla/wordpress-plugins#3]

**Comment by Ashwin02** [comment]
@digitarald Just to be sure are this all the plugins https://wordpress.org/plugins/tags/mozilla

**Comment by digitarald** [comment]
@Ashwin02 a draft for the plugins with links is @ https://mozilla.github.io/wordpress-plugins/ , where the plan is to merge offline shell and offline content into one offline plugin. This means we'll have 3 plugins to cover.

**Comment by Ashwin02** [comment]
@digitarald thank you for that information and also where exactly should I start writing the descriptions for the plugins ?
