### ISSUE TITLE
Create a shared header for wordpress plugins

### ISSUE THREAD

**Issue by digitarald** [mozilla/wordpress-plugins#4]
We need to create separate header for README.md (github) and readme.txt (wp.org) that
- Explain the suite
- Link to the other plugins

@darkwing @marco-c @delapuente @wfwalker lets wordsmith in this issue …

**Comment by darkwing** [comment]
"The Mozilla {name of suite} is a family of plugins aims to improve the speed, reliability, offline, and user outreach (push notifications) capabilities of WordPress blogs via the new ServiceWorker API.  View a listing of separate plugins and details here: {link to suite site}".

That's a short idea.

**Comment by delapuente** [comment]
Tweaking your proposal:

"The Mozilla {name of suite} is a family of plugins aimed to modernize WordPress blogs by adding super fast client caches, network independence and push notifications via the new ServiceWorker API. View a listing of separate plugins and details here: {link to suite site}".

**Comment by darkwing** [comment]
@delapuente nailed it!  :+1:  :100:

**Comment by digitarald** [comment]
I agree that we nailed the technical perspective, so I want to throw in a more product focused angle.

> The Mozilla {name of suite} is a family of plugins aimed to modernize WordPress blogs. Client caching for posts delivers them faster and work on flaky/offline network connections. Keep your readers in the loop with web based push notifications and the ability to install your blog on their phone's home screens. Select the capabilities that best match your blog and audience using these plugins: …
