### ISSUE TITLE
Allow cooldown time for disabling plugins while unregistering service workers

### ISSUE THREAD

**Issue by digitarald** [mozilla/wordpress-plugins#5]
As a user I want to be able to disable the plugin functionality while also making sure no returning user visits the site with a stale service worker.

**Problem statement**: Right now disabling the plugin leaves a service worker installed for users that visited the site while the plugin was enabled. This can lead to side effects.

**Implementation proposal**: Add a checkbox to disable the plugin, which unregisters its functionality from the service worker and cleans up any remaining data like caches.
- Do we have alternative solutions?
- How do we handle one plugin of the suite getting disabled?
- How do we make sure admins are aware of side effects?

Please discuss, @delapuente @marco-c @darkwing

**Comment by delapuente** [comment]
There are two cases to be considered here. The first case is you have disabled one plugin but other remain there. In this case, the service worker has changed and next time the client visit the page it will register the new service worker.

Second case is you have disabled all the plugins so no code is being added to register nor serving the service worker. This has been discussed on some e-mails and it's [being tracked as part of WP_SW_Manager](https://github.com/mozilla/wp-sw-manager/issues/2).

Of course, both cases require the user to visit the site again and there is _one-visit-delay_. This could be improved with a push notification or by background sync once we have it available.
