### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by theenoahmason** [mozilla/wordpress-plugins#6]
Are these plugins in working order? are they maintained? Pretty great stuff even if the community hasnt necessarily adopted it. Would love to see this maintained.

**Comment by marco-c** [comment]
Unfortunately they are not maintained anymore. If somebody picked them up, I'd be happy to help them start.

**Comment by theenoahmason** [comment]
@marco-c I will discuss with my team, but I can say I'd absolutely like to take this on.

**Comment by theenoahmason** [comment]
@marco-c anything you think I should know? 

how does this service worker script compare to create-react-app's for example?

Will be using chrome's lighthouse audits to test, Does Mozilla have something similar I should run work through?

**Comment by marco-c** [comment]
@theenoahmason sorry for not getting back to you earlier, totally slipped off.

> how does this service worker script compare to create-react-app's for example?

I'm not familiar with `create-react-app`, but it's probably different. `create-react-app` just helps creating an app with a service worker for offline support. The Wordpress plugins instead add service worker functionality to Wordpress sites/blogs.

> Will be using chrome's lighthouse audits to test, Does Mozilla have something similar I should run work through?

Not that I know of. Maybe @delapuente knows of some similar tool.

**Comment by theenoahmason** [comment]
@marco-c no worries, I haven't had a chance to dive in but I will fork this soon and post updates here when I do.

**Comment by delapuente** [comment]
Thank you @theenoahmason! This is really great news. Unfortunately, Mozilla does not have anything similar to Lighthouse for testing _how much PWA_ is your site.

**Comment by theenoahmason** [comment]
@dapuente No worries! I think we have an opportunity here to make WordPress grow up a little bit.
